package dev.bilbo.intelligence.tier3

import dev.bilbo.domain.*
import kotlinx.datetime.LocalDate

/**
 * Builds the anonymized JSON payload sent to the Supabase Edge Function for
 * Tier-3 (cloud AI) weekly narrative generation.
 *
 * No PII is included — only aggregated usage statistics and heuristic insight types.
 */
class InsightPromptBuilder {

    data class WeeklySummaryPayload(
        val weekStart: String,                    // ISO date, e.g. "2025-03-10"
        val totalScreenTimeMinutes: Int,
        val emptyCalorieMinutes: Int,
        val nutritiveMinutes: Int,
        val neutralMinutes: Int,
        val fpEarned: Int,
        val fpSpent: Int,
        val fpBalance: Int,
        val intentAccuracyPercent: Float,
        val streakDays: Int,
        val topEmotions: List<String>,            // e.g. ["STRESSED", "BORED"]
        val spikeDays: List<String>,              // e.g. ["MONDAY", "THURSDAY"]
        val heuristicInsightTypes: List<String>,  // e.g. ["CORRELATION", "ACHIEVEMENT"]
        val weekOverWeekChange: Double?,          // e.g. -0.12 means 12% reduction
        val topNutritiveApps: List<String>,       // app labels only, no package names
        val topEmptyCalorieApps: List<String>
    )

    /**
     * Builds the JSON payload for the cloud AI request.
     *
     * @param weekStart The first date of the analyzed week.
     * @param budget The [DopamineBudget] for the last day of the week (or a weekly aggregate).
     * @param insight The [WeeklyInsight] generated by Tier-2 analysis.
     * @param checkIns All emotional check-ins for the week.
     * @param sessions All usage sessions for the week.
     * @param weekOverWeekChange Optional week-over-week change ratio.
     */
    fun buildPayload(
        weekStart: LocalDate,
        budget: DopamineBudget,
        insight: WeeklyInsight,
        checkIns: List<EmotionalCheckIn>,
        sessions: List<UsageSession>,
        weekOverWeekChange: Double? = null
    ): WeeklySummaryPayload {
        val topEmotions = checkIns
            .groupBy { it.preSessionEmotion }
            .entries
            .sortedByDescending { it.value.size }
            .take(3)
            .map { it.key.name }

        val nutritiveByApp = sessions
            .filter { it.category == AppCategory.NUTRITIVE }
            .groupBy { it.appLabel }
            .entries
            .sortedByDescending { it.value.sumOf { s -> s.durationSeconds } }
            .take(3)
            .map { it.key }

        val emptyByApp = sessions
            .filter { it.category == AppCategory.EMPTY_CALORIES }
            .groupBy { it.appLabel }
            .entries
            .sortedByDescending { it.value.sumOf { s -> s.durationSeconds } }
            .take(3)
            .map { it.key }

        val spikeDays = insight.tier2Insights
            .filter { it.type == InsightType.ANOMALY }
            .mapNotNull { it.message.extractDayOfWeek() }
            .distinct()

        val insightTypes = insight.tier2Insights.map { it.type.name }.distinct()

        val balance = FPEconomy.DAILY_BASELINE +
            budget.fpEarned + budget.fpBonus + budget.fpRolloverIn - budget.fpSpent

        return WeeklySummaryPayload(
            weekStart = weekStart.toString(),
            totalScreenTimeMinutes = insight.totalScreenTimeMinutes,
            emptyCalorieMinutes = insight.emptyCalorieMinutes,
            nutritiveMinutes = insight.nutritiveMinutes,
            neutralMinutes = insight.totalScreenTimeMinutes - insight.nutritiveMinutes - insight.emptyCalorieMinutes,
            fpEarned = insight.fpEarned,
            fpSpent = insight.fpSpent,
            fpBalance = balance,
            intentAccuracyPercent = insight.intentAccuracyPercent,
            streakDays = insight.streakDays,
            topEmotions = topEmotions,
            spikeDays = spikeDays,
            heuristicInsightTypes = insightTypes,
            weekOverWeekChange = weekOverWeekChange,
            topNutritiveApps = nutritiveByApp,
            topEmptyCalorieApps = emptyByApp
        )
    }

    /**
     * Converts the [WeeklySummaryPayload] to a JSON string suitable for the Edge Function.
     * Uses manual serialization to avoid a runtime kotlinx.serialization dependency at this layer.
     */
    fun toJson(payload: WeeklySummaryPayload): String {
        fun String.jsonStr() = "\"${this.replace("\"", "\\\"")}\""
        fun List<String>.jsonArr() = "[${joinToString(",") { it.jsonStr() }}]"
        fun Double?.jsonNum() = this?.toString() ?: "null"

        return buildString {
            append("{")
            append("\"weekStart\":${payload.weekStart.jsonStr()},")
            append("\"totalScreenTimeMinutes\":${payload.totalScreenTimeMinutes},")
            append("\"emptyCalorieMinutes\":${payload.emptyCalorieMinutes},")
            append("\"nutritiveMinutes\":${payload.nutritiveMinutes},")
            append("\"neutralMinutes\":${payload.neutralMinutes},")
            append("\"fpEarned\":${payload.fpEarned},")
            append("\"fpSpent\":${payload.fpSpent},")
            append("\"fpBalance\":${payload.fpBalance},")
            append("\"intentAccuracyPercent\":${payload.intentAccuracyPercent},")
            append("\"streakDays\":${payload.streakDays},")
            append("\"topEmotions\":${payload.topEmotions.jsonArr()},")
            append("\"spikeDays\":${payload.spikeDays.jsonArr()},")
            append("\"heuristicInsightTypes\":${payload.heuristicInsightTypes.jsonArr()},")
            append("\"weekOverWeekChange\":${payload.weekOverWeekChange.jsonNum()},")
            append("\"topNutritiveApps\":${payload.topNutritiveApps.jsonArr()},")
            append("\"topEmptyCalorieApps\":${payload.topEmptyCalorieApps.jsonArr()}")
            append("}")
        }
    }

    // ---------------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------------

    private val dayNames = listOf(
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
    )

    private fun String.extractDayOfWeek(): String? {
        return dayNames.firstOrNull { this.contains(it, ignoreCase = true) }?.uppercase()
    }
}
